apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: Lts74367908

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apijs-config
data:
  MONGO_URI: mongodb://root:example@mongodb-service:27017/
