# Use the official MongoDB base image
FROM mongo:6.0

# Set the working directory for MongoDB configuration
WORKDIR /docker-entrypoint-initdb.d

# Copy initialization scripts (optional)
COPY ../init-mongo.js /docker-entrypoint-initdb.d/

# Expose MongoDB default port
EXPOSE 27017
